### ISSUE TITLE
Packaging third-party software into docker image

### ISSUE THREAD

**Issue by tonyyzy** [EnsemblGSOC/tony-gsoc-2018#18]
@andrewyatz @leannehaggerty 

Leanne, you mentioned that the .dat output of TRF will need to be converted to the BED format. That [stub](https://github.com/hdashnow/TandemRepeatFinder_scripts/blob/master/TRFdat_to_bed.py) is not available as a docker image yet. I'm thinking about packaging it myself. Is there any copyright stuff I need to be aware of? Would it be a problem if I upload the docker image to my own docker hub repo?

The same goes for CpG island. I want to compile and package the [c code here](http://genome-source.cse.ucsc.edu/gitweb/?p=kent.git;a=tree;f=src/utils/cpgIslandExt) into a docker image. Will there be any issues?

**Comment by leannehaggerty** [comment]
Okay, I asked around and Marek said this:

To the best of my knowledge the rules for redistributing FOSS software
as Docker images are the same as for redistributing binary packages of
such software. As long as the licence does not place any restrictions on
this (which are typically caused by certain bits of code being
patent-encumbered, e.g. Elliptic Curve algorithms in OpenSSL or
ClearType support in FreeType), you should be okay.

**Comment by tonyyzy** [comment]
Hey Leanne, thanks a lot for this!
Both software licenses say the original license must be included in the distribution. So I guess as long as the license file is in the docker image then it would be alright.
